### ISSUE TITLE
Accessing the data via API

### ISSUE THREAD

**Issue by elanmart** [allegroai/trains-server#10]
Hi, thanks for the great opensource release!

I have one question regarding accessing the data from python. 
Please excuse my utter ignorance in this matter. 

I'd like to fetch data from `trains-server` for visualization / exploratory data analysis purposes. 
Could you point me to some examples on how to do this in the most sane manner? 

By digging through the code I found this:
https://github.com/allegroai/trains-server/tree/master/server/services
and looking at the `@endpoint` decorators I cooked up something like:

```python
import requests
from pyhocon import ConfigFactory

cfg = ConfigFactory.parse_file("/home/elan/trains.conf")
base = cfg['api']['host']
user = cfg['api']['credentials']['access_key']
secret = cfg['api']['credentials']['secret_key']


def _get(endpoint, **kwargs):
    return requests.get(
        f'{base}/{endpoint}', 
        auth=(user, secret),
        params=dict(kwargs),
    ).json()['data']
    

def get_projects():
    return _get(
        'projects.get_all'
    )['projects']
    

def get_tasks():
    return _get(
        'tasks.get_all'
    )['tasks']


def get_scalar_metrics_and_variants(task_id):
    return _get(
        'events.get_scalar_metrics_and_variants', 
        task=task_id
    )


def get_scalar_metric_data(task_id, metric):
    return _get(
        'events.get_scalar_metric_data',
        task=task_id,
        metric=metric
    )
```

which I can then use as:

```python
P = get_projects()
T = get_tasks()

first_task = T[0]['id']

avail_metrics = get_scalar_metrics_and_variants(first_task)

mse_loss = get_scalar_metric_data(first_task, 'MSE loss')
```

Is this the right approach? Or does `trains` provide some kind of abstractions to make this easier?

As mentioned, please excuse me my utter ignorance in this subject. 

best,
Marcin

**Comment by bmartinn** [comment]
@elanmart thank you, it's always great to get positive feedback :)

Regrading metrics and access, the API is already part of the *TRAINS* package, although still not fully documented.

Below is a simple example that: lists all projects (based on project name), lists all experiments in the specific project, arbitrarily picks an experiment and print its scalar metrics.


```
from trains.backend_api import Session
from trains.backend_api.services import tasks, events, projects

# create an authenticated session
session = Session()

# get projects matching 'examples' name
res = session.send(projects.GetAllRequest(name='examples'))
projects_id = [p.id for p in res.response.projects]
print('project ids: {}'.format(projects_id))

# get all experiments/tasks
res = session.send(tasks.GetAllRequest(project=projects_id))

# pick an experiments/tasks
task = res.response.tasks[11]
print('task name: {}'.format(task.name))

# get experiment metric values
res = session.send(events.ScalarMetricsIterHistogramRequest(
    task=task.id,
))
scalars = res.response_data
print('scalars {}'.format(scalars))

```

Is this what you were looking for?

**Comment by elanmart** [comment]
Thank you so much, this is precisely what I've been looking for. 

Closing the issue as resolved, thanks!

**Comment by noamsgl** [comment]
I see the REST API provides getting up to 500 tasks. Is there a way to overcome this?
