### ISSUE TITLE
Deploying trains on Kubernetes

### ISSUE THREAD

**Issue by abimur-123** [allegroai/trains-server#12]
I was wondering if you have a helm chart or pre-built docker images that could be used to deploy trains-server to a Kubernetes cluster hosted on Azure?

**Comment by bmartinn** [comment]
Helm is coming soon :) 
As for pre-built docker installation, you can find full installation details [here](https://github.com/allegroai/trains-server#launching-docker-containers)

**Comment by bmartinn** [comment]
@abimur-123 We now have TRAINS k8s/helm support
Feel free to check it out :)
https://github.com/allegroai/trains-server-k8s
https://github.com/allegroai/trains-server-helm

**Comment by bmartinn** [comment]
Closing, feature implemented.
