### ISSUE TITLE
Add support for Windows 10

### ISSUE THREAD

**Issue by alexkaz2** [allegroai/trains-server#13]
AFAIK, Currently it is supported only on Linux.
From readme: "For Windows users, we recommend running the server on a Linux virtual machine." but it would be great to do without this workaround.

Additionally, it might be a good idea to mention this issue on the main Github page of TRAINS. 

Thanks for the great project!

**Comment by bmartinn** [comment]
@alexkaz2 Could you please elaborate on "No Windows support"?
The *TRAINS* pypi package supports Windows. 
The part that is not supported is the *TRAINS-server* (as it needs mongoDB and ElasticSearch that do not support Windows as a hosting OS).

What is the specific setup you had in mind?

**Comment by alexkaz2** [comment]
Thanks for the quick response.
I refer here **only to the trains-server**, the logging module of TRAINS runs smoothly on windows :)
As you mentioned there is no way to launch the server locally, without launching a VM with Linux. For me unfortunately it is a deal-breaker.

It would be great is there was a way to view the accumulated experiments locally, via local server or GUI, for example as Sacred did [here](https://github.com/IDSIA/sacred)

**Comment by bmartinn** [comment]
@alexkaz2 did you try docker for windows ? In theory it might work ...

**Comment by alexkaz2** [comment]
@bmartinn I believe it will work, but similarly to VM it is a less elegant solution than a simple GUI that mounts the DB and provides same API as the trains-server.

IMHO the Docker \ VM solution eliminates your main advantage of '... in only two lines of code!'.

I totally understand that Windows support is nor a minor feature, neither it is a primary goal for you right now, so feel free to delete \ close this issue with [feature][postponed][...] flags :)

**Comment by alexkaz2** [comment]
@bmartinn I didn't try it yet, will do :)

Thanks! I am closing the issue for now...
