### ISSUE TITLE
GCP support?

### ISSUE THREAD

**Issue by S-aiueo32** [allegroai/trains-server#14]
I want to deploy on GCP.
Do you plan to support?

**Comment by S-aiueo32** [comment]
#12

**Comment by bmartinn** [comment]
Unfortunately,  we still do not have pre-buil GCP images, that said it is quite easy to setup. 
Setup a GCP machine, ssh to it, and follow the docker [instructions](https://github.com/allegroai/trains-server#setup) :)

**Comment by S-aiueo32** [comment]
Thank you for your reply.

I tried to follow the instructions but I'm facing internal server errors.
Like your mention in #6 , I run `docker ps` and the result was below.
```
CONTAINER ID        IMAGE                                                  COMMAND                  CREATED             STATUS                          PORTS               NAMES
f15bc61f1986        allegroai/trains:latest                                "/opt/trains/wrapper…"   3 minutes ago       Up 3 minutes                                        trains-webserver
8f7587fd20bd        allegroai/trains:latest                                "/opt/trains/wrapper…"   3 minutes ago       Up 11 seconds                                       trains-apiserver
644dd63e96f0        allegroai/trains:latest                                "/opt/trains/wrapper…"   3 minutes ago       Up 3 minutes                                        trains-fileserver
30d5829244aa        mongo:3.6.5                                            "docker-entrypoint.s…"   4 minutes ago       Up 3 minutes                                        trains-mongo
e0a179993c24        docker.elastic.co/elasticsearch/elasticsearch:5.6.16   "/bin/bash bin/es-do…"   4 minutes ago       Restarting (1) 46 seconds ago                       trains-elastic
```
It seems that `trains-apiserver` and `trains-elastic` keep to be crashed, not `mongo`.
Do you have any idea what is happening?

**Comment by bmartinn** [comment]
Usually, this kind of behavior from the Elastic container indicates issues with the docker daemon configuration. These are affected by steps 2 through 5 in our [Setup](https://github.com/allegroai/trains-server#setup) section.

Use the `docker logs trains-elastic` command and try to figure out which configuration is failing (you're welcome to share the logs output here, of course).

**Comment by S-aiueo32** [comment]
Thank you!
Your pointing was correct and I've been able to run it. (I had a typo in daemon setting...)
