### ISSUE TITLE
Add option to smooth scalar graphs (similar to TensorBoard, but better) 

### ISSUE THREAD

**Issue by daganesh** [allegroai/trains-server#15]
In TensorBoard one can control the amount of smoothing that is applied to all scalar graphs.
This is a desirable feature, since graphs can be very jittery.
Request: in the Metrics view (Experiments->Results->Metrics) add a settings option for "Smoothing" with a slider. Higher values will induce smoother graphs, while smaller values will result in minor smoothing, or not at all (for the value of zero).

![image](https://user-images.githubusercontent.com/14297886/61293767-17c66600-a7dd-11e9-86de-89c033802532.png)

**Comment by bmartinn** [comment]
This feature will be part of future release :)

**Comment by bmartinn** [comment]
@daganesh I'm happy to announce that scalar smoothing, as well as relative/wall time, were added to trains-server v0.11.0 
It is now finally out :confetti_ball:
