### ISSUE TITLE
Is there a way to retroactively upload an experiment, e.g. due to communication problems?

### ISSUE THREAD

**Issue by daganesh** [allegroai/trains-server#16]
Consider the following scenario:
I have a training machine, running and experiment, and network communication for this machine is off, for some reason.
In this case I am not able to update the trains-server with the running experiment.
It could be nice, if I could retroactively send the missing experiment results (in TF it is mainly the events files).
Alternatively I could upload a new experiment completely from scratch.
This can be done either from the trains API in the client, or by some UI option in the trains-server.

**Comment by bmartinn** [comment]
Currently, this is not supported, but I guess this is possible.
Feel free to fork the TRAINS code base, and take a stab at it :)

**Comment by bmartinn** [comment]
Closing, due to lack of activity.
