### ISSUE TITLE
Login on fixed users mode doesn't work

### ISSUE THREAD

**Issue by OfirKP** [allegroai/trains-server#17]
After several attempts to define fixed users in `apiserver.conf` (and trying your example), signing in is unsuccessful.

After deleting and installing the new docker image and containers, I followed the instructions in your latest release to add a list of fixed users (and used no special characters). 
I restarted the _trains-apiserver_ container. And yet, when I got to the login screen (the new one, and not the "Enter Full Name" screen), signing in with the correct details gives an "Invalid User/Password combination" error.
The response from the auth.login service is the following:
```
{  
   "meta":{  
      "id":"802d6a6810d24c1a885292ef35c358dc",
      "trx":"802d6a6810d24c1a885292ef35c358dc",
      "endpoint":{  
         "name":"auth.login",
         "requested_version":"2.2",
         "actual_version":"1.0"
      },
      "result_code":401,
      "result_subcode":22,
      "result_msg":"Unauthorized (invalid credentials) (failed to locate provided credentials)",
      "error_stack":null
   },
   "data":{  

   }
}
```
I get the same error when using your example with username: jane, password: 12345678.

**Comment by bmartinn** [comment]
Hi,
This looks like a configuration loading issue (type of error indicates the fixed users configuration was not located by the server).
Can you share some environment details:
- apiserver.conf file contents (even if it's the same as described in our example)
- apiserver.conf file location in your file system
- docker run command used to start the trains apiserver docker container

**Comment by OfirKP** [comment]
Thank you for the response!
I would like to mention that after deleting apiserver.conf and restarting the trains-apiserver container, I'm getting back the regular "Full name" screen and not the username & password login screen.

Here are the details:

File location: `/opt/trains/config/apiserver.conf`

### Content
```
auth {
    # Fixed users login credetials 
    # No other user will be able to login
    fixed_users {
        enabled: true
        users: [
            {
                username: "jane"
                password: "12345678"
                name: "Jane Doe"
            },
            {
                username: "john"
                password: "12345678"
                name: "John Doe"
            },
        ]
    }
}
```
Docker command used: `sudo docker run -d --restart="always" --name="trains-apiserver" --network="host" -v /opt/trains/logs:/var/log/trains -v /opt/trains/config:/opt/trains/config allegroai/trains:latest apiserver
`

**Comment by bmartinn** [comment]
Looks OK. This might be caused by incomplete data left in the database on server initialization... Can you share the server logs (in `/opt/trains/logs`)?

**Comment by OfirKP** [comment]
I think you are right. Can you elaborate further on how I could reset/remove that data? (I tried to delete the opt/trains folder but it didn't help)

Logs:
[apiserver.log](https://github.com/allegroai/trains-server/files/3406691/apiserver.log)
[apiserver(1).log](https://github.com/allegroai/trains-server/files/3406695/apiserver.1.log)

**Comment by bmartinn** [comment]
The database data resides in the `/opt/trains/data` folder. To delete it and start over:

- Stop and remove all docker containers (as described in the [Upgrade](https://github.com/allegroai/trains-server#upgrade) section, step 1
- Delete the contents of the `/opt/trains/data` folder
- Delete the logs from `/opt/trains/logs` (just to make it easier to see what's going on)
- Run the docker containers

**Comment by OfirKP** [comment]
It failed after reinstalling the containers (and deleting the folders as you suggested), but I managed to figure out the problem. 
After installing trains on a completely new environment I still got the same issue, and when I ran `docker ps` I found out that the `trains-mongo` container was stuck in a restart loop, because of a conflict it had with a running instance of mongo on my host with the same port (27017). 

Killing the host's mongo solved the problem.

However, I would prefer not to change my host's mongo defaults.
I manually resolved this by adding the command `mongod --port 27018` (or other unused port) to your docker run command.
e.g. `sudo docker run -d --restart="always" --name="trains-mongo" -v /opt/trains/data/mongo/db:/data/db -v /opt/trains/data/mongo/configdb:/data/configdb --network="host" mongo:3.6.5 mongod --port 27018`

Also, I had to change the 27017 port to 27018 in the `trains-apiserver`'s `server/config/default/hosts.conf` to make it work. 
Is there a more convenient way to override this configuration without manually editing this file? (and one that will survive an update)

**Comment by bmartinn** [comment]
Glad to hear you figured it out, and thanks for the update! - we'll add it to the FAQ.
As for configuring an alternative port number - I'll add a feature request to allow setting this value using an environment variable, which will make it easier to control using the `docker run` command.

**Comment by scheckley** [comment]
sorry for opening a long closed ticket. I am seeing this issue currently. After adding 2 additional new users to the server conf a rebooting, they login is not recognised and is returning

`[WARNING] [clearml.service_repo] Returned 401 for auth.login in 2ms, msg=Unauthorized (invalid credentials) (failed to locate provided credentials)`

Is there any solution since 2019 to repair the database without losing experiments?

Thanks for any help.
