### ISSUE TITLE
Can this be deployed on Mac more smoothly?

### ISSUE THREAD

**Issue by xiao2mo** [allegroai/trains-server#19]
I followed the instructions related to Ubuntu but still can't get it work. I don't know what's wrong with it.. sadly.

**Comment by osdf** [comment]
See #18 for the current main block on OSX.

**Comment by bmartinn** [comment]
@xiao2mo Please check #18 , there is a working solution [here](https://github.com/allegroai/trains-server/issues/18#issuecomment-514835941)

**Comment by bmartinn** [comment]
Closing, referenced issue marked as working solution.
