### ISSUE TITLE
secret key issues containing *

### ISSUE THREAD

**Issue by shaulimaya** [allegroai/trains-server#21]
Hey!
After some tries, we still have issues with secret key having *
Is it possible just to create the secret key without *?

It affects us when we are using env variables and not conf file

Thanks!

**Comment by bmartinn** [comment]
I forgot to update here, v0.11.0 is out, it has both min/max/last values and hyper-parameters as columns
 :sparkles:

**Comment by bmartinn** [comment]
I forgot to update here, v0.11.0 is out, and it should solve the issue with "*" in the secret :smile:

**Comment by shaulimaya** [comment]
We had this week issue other special characters ...i don't remember which(maybe  #)
For now closing it...if we will have another issue - then we will reopen :)
