### ISSUE TITLE
How to run trains on local server.

### ISSUE THREAD

**Issue by columbo123** [allegroai/trains-server#30]
I have installed trains server on my Ubuntu machine using this link `(https://github.com/allegroai/trains-server/blob/master/docs/install_linux_mac.md) ` . I am currently running a simple example code `https://github.com/allegroai/trains/blob/master/examples/automl/toy_base_task.py`. I am not sure how to run **trains-init** or where to find and edit **~/trains.conf** so that I can run stuff on local server. Can anyone describe it briefly. 
Thanks in advance

**Comment by xandox** [comment]
Run `trains-init` on machine where you going to run `toy_base_task.py`. There will be a wizard with few questions. After that you can run `toy_base_task.py` and it will use your local server.

**Comment by columbo123** [comment]
Thanks a lot, got it
