### ISSUE TITLE
Manage disk space usage

### ISSUE THREAD

**Issue by RadaKk** [allegroai/trains-server#32]
Hi,
 
It has been 3 weeks since I deploy trains server for my research team and I am monitoring the disk space used by the server data.

Today it takes more than 2GB (around 30 tasks) which seems to be huge for just graphs' coordinates and hyperparameters. 
We use the default Pytorch-Tensorboard logger with resources monitoring disabled and all models are empty, they just display the path of the stored checkpoint.

90% of the space is used by Elastic Search indices and since there is no way to delete a training task, do you know how to "clean" the indices or how to reduce the amount of space used for each tasks ?

Thank you

**Comment by JDennisJ** [comment]
Hi @RadaKk,

You can not delete tasks from the UI, but you can delete an experiment from code, which will delete the indices from Elastic.
This can be achieved with the help of [trains-agent](https://github.com/allegroai/trains-agent) package:

For example, if you like to delete task id "123456789", do the following:

```
from trains_agent import APIClient

client = APIClient()
client.tasks.delete(task='123456789')
```

**Comment by RadaKk** [comment]
Ah great, I will give it a try! 
I think it should be indicated in the global trains documentation (or I missed it).
Thank you

**Comment by RadaKk** [comment]
Hi, 
I used your code it seems that some models have not been deleted with their corresponding task.
Is there a function to delete specific models with their model ID?

From my understanding, the task should be "reset" before "delete":
```python
    client.tasks.reset(task.id)  
    client.tasks.delete(task.id)
```

**Comment by JDennisJ** [comment]
Hi @RadaKk ,

The `tasks.delete` is actually `tasks.reset` and after `tasks.delete`,  so only `tasks.delete` should work too.

About the models issue, we are currently adding a new endpoint for doing so. 
Hopefully should not take long to release :)

**Comment by Paucaster3** [comment]
Hi, I am experiencing something similar to @RadaKk . I have been performing several tests with clearml so I have a large number of tasks. When I iniciate the clearml-elastic container, there's a memory usage of 24 GB only for that container. Is this usual? How can i configure it?

Thank you
