### ISSUE TITLE
Is the latest docker-compose.yml up-to-date?

### ISSUE THREAD

**Issue by majdzr** [allegroai/trains-server#33]
Hey,

I'm trying to update the server to 0.13.2. without any luck. I'm working with the docker image and following your upgrade instructions, but I keep installing the 0.13. Any tips?

Thanks in advance,
Majd

**Comment by bmartinn** [comment]
Hi @majdzr,

The latest _trains-server_ release is v0.13.0, so you are getting the correct version (see all _trains-server_ releases [here](https://github.com/allegroai/trains-server/releases))

**Comment by majdzr** [comment]
You're correct. Sorry.
However, I was almost sure that there is a newer version as I was receiving this confusing message:

> TRAINS-SERVER new version available: upgrade to v0.13.2 is recommended!

 every time I run _trains_.  But I guess it was a misunderstanding as it disappeared once I updated _trains_ to 0.13.2 .

**Comment by bmartinn** [comment]
Hi @majdzr ,

In that case, this seems like a bug in _trains_ since you shouldn't have received such a message. I'll check it out and push a fix.

Thanks!
