### ISSUE TITLE
How to config SSL?

### ISSUE THREAD

**Issue by GeoffreyChen777** [allegroai/trains-server#34]
I use Nginx as the web server. It can let me to access trains(port 8080) by subdomain(e.g., trains.xxx.com). I also use a let's encrypt to set ssl for my web server. 

When I open https://trains.xxx.com, I got some errors from my chrome console:

![image](https://user-images.githubusercontent.com/14183213/75249680-aee2aa00-5811-11ea-9e08-f7f7c878845c.png)

There is no password box in the webpage. I cannot login to my trains web page.

I can use ip:port to access my trains web page with some errors, but the password box is existed:
![image](https://user-images.githubusercontent.com/14183213/75250011-5e1f8100-5812-11ea-9d7e-93e6189b5115.png)
when I log in:
![image](https://user-images.githubusercontent.com/14183213/75250110-945d0080-5812-11ea-9587-59a0ea8c94a2.png)

Is there any doc about how to config ssl?

Thanks for your help.

**Comment by bmartinn** [comment]
Hi @GeoffreyChen777 
As you can see in the installation instruction [here](https://github.com/allegroai/trains-server#system-design), just under the diagram:
trains-server supports two types of configurations:
```
    Single IP (domain) with the following open ports
        Web application on port 8080
        API service on port 8008
        File storage service on port 8081

    Sub-Domain configuration with default http/s ports (80 or 443)
        Web application on sub-domain: app.*.*
        API service on sub-domain: api.*.*
        File storage service on sub-domain: files.*.*
```

This means you have to setup the Nginx to forward the following subdomains (yes, only these subdomains are supported):
```
  app.*.* -> http://<trains_server_ip>:8080
  api.*.* -> http://<trains_server_ip>:8008
  files.*.* -> http://<trains_server_ip>:8081
```

**Comment by GeoffreyChen777** [comment]
@bmartinn Hi, thanks for your reply.

I tried to set my Nginx with the configuration:

```
server {
    listen 80;

    server_name app.mydomain.com;

    location / {
        proxy_pass       http://127.0.0.1:8080;
        proxy_set_header Host      $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}


server {
    listen 80;

    server_name api.mydomain.com;

    location / {
        proxy_pass       http://127.0.0.1:8008;
        proxy_set_header Host      $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

server {
    listen 80;

    server_name files.mydomain.com;

    location / {
        proxy_pass       http://127.0.0.1:8081;
        proxy_set_header Host      $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

```

Can not solve it.

**Comment by bmartinn** [comment]
@GeoffreyChen777 regrading the DNS entry:
First make sure you get the correct IP with : 
`ping app.mydomain.com`
(If you do not, then yes you need to configure the DNS records of your domain)

BTW:
I would recommend using:
`app.trains.mydomain.com` , `api.trains.mydomain.com` , `files.trains.mydomain.com` ,

**Comment by GeoffreyChen777** [comment]
@bmartinn

Now I have added `app.trains.mydomain.com , api.trains.mydomain.com , files.trains.mydomain.com` to my DNS console. When I `ping app.trains.mydomain.com`, I can get the correct IP.

I also set my nginx to forward the subdomian to the corresponding port. When I open `https://api.trains.mydomain.com`, I can get:
```
{"meta":{"id":"7c828bb4526846f29018f44ffaccb4b7","trx":"7c828bb4526846f29018f44ffaccb4b7","endpoint":{"name":"","requested_version":1.0,"actual_version":null},"result_code":400,"result_subcode":0,"result_msg":"Invalid request path /","error_stack":null},"data":{}}
```

I think it means that I can access apiserver(port 8008) through `api.trains.mydomain.com`.

I think, now, I need to change some configuration files of trains-server.
Because I found that the trains-server still tries to access port 8008:
![image](https://user-images.githubusercontent.com/14183213/75254438-56b0a580-581b-11ea-97af-951847afbd5f.png)

**Comment by bmartinn** [comment]
The Web App will access the API server based on the address it is served from:
i.e. If browsing to http://localhost:8080 it will look for the Api server at https://localhost:8008
and if browsing to http://app.trains.mydomain.com it will look for http://api.trains.mydomain.com

Try clearing cookies, restarting the browser and opening http://app.trains.mydomain.com

**Comment by GeoffreyChen777** [comment]
After I refresh my cookies cache, everything works fine now!

Thanks for you help! @bmartinn 

Have a nice day!
