### ISSUE TITLE
GCloud installation instructions not working

### ISSUE THREAD

**Issue by H4dr1en** [allegroai/trains-server#39]
Instructions from [install_gcp.md](https://github.com/allegroai/trains-server/blob/master/docs/install_gcp.md) do not work: the following error is thrown:

> Creating image "allegro-trains-server" failed. Error: Invalid value for field 'resource.rawDisk.source': 'https://storage.googleapis.com/allegro-files/trains-server/trains-server.vmdk'. The provided source is not a supported file.

As written in the hint for Google Cloud Image, 
> Your image source must use the .tar.gz extension and the file inside the archive must be named disk.raw

I guess the source should probably be "Virtual Disk (VMDK, VHD) instead of "Google storage file". But then it requires `Cloud Build` to be enabled (and more permissions from user).

<img width="721" alt="Screenshot 2020-05-04 at 11 53 19" src="https://user-images.githubusercontent.com/16240134/80954608-fd0dbe00-8dfd-11ea-9152-bfffad3a5b71.png">

**Comment by bmartinn** [comment]
Hi @H4dr1en,

You're quite right, thanks for reporting this!

I checked again and tried it myself, and there are two options:

- Choose **Cloud storage File** and use the value `allegro-files/trains-server/trains-server.tar.gz`

OR
- Choose **Virtual disk (VMDK, VHD)**, use the value `allegro-files/trains-server/trains-server.vmdk` and under **Operating system on virtual disk** select `No operating system. Data only.`

The first one is much faster and IMO simpler, and I'll update the documentation accordingly - please let me know if it works for you.

Thanks again :)

**Comment by H4dr1en** [comment]
Thank you for your reply. I would also prefer the first solution, although not working for me at the moment:

<img width="458" alt="Screenshot 2020-05-04 at 16 00 34" src="https://user-images.githubusercontent.com/16240134/80974041-7b7b5780-8e20-11ea-8f9a-dc5827b2c64f.png">

**Comment by bmartinn** [comment]
Sorry, had to make it public :)
Try now...

**Comment by H4dr1en** [comment]
Thanks, it worked 👍

**Comment by bmartinn** [comment]
Documentation updated :)
