### ISSUE TITLE
The meaning of status 'published'

### ISSUE THREAD

**Issue by philipskokoh** [allegroai/trains-server#4]
This tool is really great!! 
I have a question about status 'published' in an experiment. What does the server do when I publish an experiment? Is this just a tag label for an experiment? or any other stuffs going on behind the scene?

**Comment by raviv** [comment]
Publishing an experiment makes it read-only as to prevents further changes to it.

**Comment by philipskokoh** [comment]
> Publishing an experiment makes it read-only as to prevents further changes to it.

Great! Thanks for the clarification!
