### ISSUE TITLE
Min / Max Values are not displaying on dropdown menu

### ISSUE THREAD

**Issue by iakremnev** [allegroai/trains-server#40]
A minor UI bug:
1. Select Min Values or Max Values in the drop-down menu on the Scalars tab in the Compare Experiment page ([demo server](https://demoapp.trains.allegro.ai/projects/0e152d03acf94ae4bb1f3787e293a9f5/compare-experiments;ids=aa28dce4c6704e7cb5b2ce16cce1f9b8,741ee8b588cd418683abd4e4160a16ba/scalars/values?scalars=min_values) as an example)
2. The comparison tables display values as expected, however the dropdown menu still says 'Last Values', which is a bit confusing.

**Comment by bmartinn** [comment]
Hi @iakremnev , bug verified.
Really appreciate the link to the demo server! it made it very easy to locate.
I'm hoping we have it fixed in the next version :)

**Comment by bmartinn** [comment]
Hi @iakremnev 
v0.15 is out :confetti_ball:  , with a bug fix. You can test on the [demo server](https://demoapp.trains.allegro.ai) :)

**Comment by iakremnev** [comment]
Works like a charm, I'm closing the issue. As always, thanks for the quick feedback! I'm fascinated with your work :)
