### ISSUE TITLE
Uploading checkpoints models to server

### ISSUE THREAD

**Issue by Deams51** [allegroai/trains-server#41]
Is it possible to upload checkpoints model to the trains-server instance?
The idea is to not be dependent on the instances as they might come and go and their storage could be erased, but to use the server as the static element in the chain.

As of now, it seems like models are stored on the agents only.
I also was unable to download any of them directly through the web interface.

**Comment by bmartinn** [comment]
Good news  @Deams51 it is fully supported :)
When you set the `output_uri` to a target server *trains* will automatically upload any checkpoint to that server, that means that every model/checkpoint stored locally will be uploaded to that server and put under a specific folder based on the experiment project & id.

Here are your options for setting the `output_uri`
- You can specify the `output_uri` in your `Task.init` call, see [here](https://allegro.ai/docs/examples/examples_models/#centralized-model-storage)
- You can set set it in the machine itself (either on development machine or a trains-agent worker), by editing the `~/trains.conf` see [here](https://github.com/allegroai/trains/blob/master/docs/trains.conf#L152)
- You can change it in the UI, per experiment, in the "Execution" tab , at the bottom "output destination" field.

For example `output_uri="http://localhost:8081/"` will upload all the checkpoints to your *trains-server*, and you will be able to download them as well. Notice that if you want to use object storage like S3 etc, you must provide the correct credentials in the `~/trains.conf`

**Comment by Deams51** [comment]
Thank you @bmartinn, great news!
I didn't realize from the documentation that the train server could directly be set as the output_uri.
