### ISSUE TITLE
Failed to create credentials on linux

### ISSUE THREAD

**Issue by devhello145** [allegroai/trains-server#45]
I tried to install trains-server on Ubuntu 20.04.
I checked port `sudo lsof -Pn -i4 | grep :8080 | grep LISTEN` - Nothing was find.
I used  instruction (https://github.com/allegroai/trains-server/blob/master/docs/install_linux_mac.md) step-by-step (excepting step 8. Instead `1000` I used my username)

[trains_log.txt](https://github.com/allegroai/trains-server/files/4803406/trains_log.txt) - `sudo docker-compose -f docker-compose.yml up`

[trains_log1.txt](https://github.com/allegroai/trains-server/files/4803415/trains_log1.txt) - `sudo HOSTIP=172.17.0.1 docker-compose -f docker-compose.yml up`

There are multiple errors in logs.
Also I can't create credentials on localhost:8080

**Comment by bmartinn** [comment]
Hi @devhello145 
From your log it seems the reason for the failure is the elasticsearch docker failed to spin (see below).
- Check the amount of memory for the server (recommend is 8GB in total, could work with less but it depends on the actual system)
- Make sure port 9200 is also available `sudo lsof -Pn -i4 | grep :9200 | grep LISTEN` 

```console
[32mtrains-elastic    |[0m [2020-06-19T08:16:40,332][INFO ][o.e.n.Node               ] [trains] initializing ...
[32mtrains-elastic    |[0m [2020-06-19T08:16:40,351][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [trains] uncaught exception in thread [main]
[32mtrains-elastic    |[0m org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: Failed to create node environment
[32mtrains-elastic    |[0m 	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:136) ~[elasticsearch-5.6.16.jar:5.6.16]
[32mtrains-elastic    |[0m 	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:123) ~[elasticsearch-5.6.16.jar:5.6.16]
[32mtrains-elastic    |[0m 	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:70) ~[elasticsearch-5.6.16.jar:5.6.16]
[32mtrains-elastic    |[0m 	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:134) ~[elasticsearch-5.6.16.jar:5.6.16]
[32mtrains-elastic    |[0m 	at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-5.6.16.jar:5.6.16]
[32mtrains-elastic    |[0m 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91) ~[elasticsearch-5.6.16.jar:5.6.16]
[32mtrains-elastic    |[0m 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84) ~[elasticsearch-5.6.16.jar:5.6.16]
[32mtrains-elastic    |[0m Caused by: java.lang.IllegalStateException: Failed to create node environment
[32mtrains-elastic    |[0m 	at org.elasticsearch.node.Node.<init>(Node.java:268) ~[elasticsearch-5.6.16.jar:5.6.16]
[32mtrains-elastic    |[0m 	at org.elasticsearch.node.Node.<init>(Node.java:245) ~[elasticsearch-5.6.16.jar:5.6.16]
[32mtrains-elastic    |[0m 	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:233) ~[elasticsearch-5.6.16.jar:5.6.16]
[32mtrains-elastic    |[0m 	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:233) ~[elasticsearch-5.6.16.jar:5.6.16]
[32mtrains-elastic    |[0m 	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:342) ~[elasticsearch-5.6.16.jar:5.6.16]
[32mtrains-elastic    |[0m 	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:132) ~[elasticsearch-5.6.16.jar:5.6.16]
[32mtrains-elastic    |[0m 	... 6 more
```

**Comment by devhello145** [comment]
1. I checked a free space:

illya@trains:$ df -h
Filesystem      Size  Used Avail Use% Mounted on
udev             16G     0   16G   0% /dev
tmpfs           3,2G  2,6M  3,2G   1% /run
/dev/sda6       435G  315G  120G  73% /
tmpfs            16G  252M   16G   2% /dev/shm
tmpfs           5,0M  4,0K  5,0M   1% /run/lock
tmpfs            16G     0   16G   0% /sys/fs/cgroup
/dev/loop2       55M   55M     0 100% /snap/core18/1754
/dev/loop1       94M   94M     0 100% /snap/core/9066
/dev/loop0       98M   98M     0 100% /snap/core/9289
/dev/loop3       63M   63M     0 100% /snap/gtk-common-themes/1506
/dev/loop4      291M  291M     0 100% /snap/vlc/1700
/dev/loop6      256M  256M     0 100% /snap/gnome-3-34-1804/36
/dev/loop5       44M   44M     0 100% /snap/hamster-snap/47
/dev/loop7       55M   55M     0 100% /snap/core18/1705
/dev/loop8      2,3M  2,3M     0 100% /snap/gnome-system-monitor/148
/dev/loop9      162M  162M     0 100% /snap/gnome-3-28-1804/128
/dev/loop10     2,3M  2,3M     0 100% /snap/gnome-system-monitor/145
/dev/sda6       435G  315G  120G  73% /home
/dev/loop11     291M  291M     0 100% /snap/vlc/1620
/dev/loop12      44M   44M     0 100% /snap/hamster-snap/43
/dev/loop13      55M   55M     0 100% /snap/gtk-common-themes/1502
/dev/loop14      50M   50M     0 100% /snap/snap-store/454
/dev/loop15     161M  161M     0 100% /snap/gnome-3-28-1804/116
/dev/sda1       464M  206M  231M  48% /boot
/dev/loop16     256M  256M     0 100% /snap/gnome-3-34-1804/33
tmpfs           3,2G   20K  3,2G   1% /run/user/121
/dev/loop17      44M   44M     0 100% /snap/snap-store/415
tmpfs           3,2G   32K  3,2G   1% /run/user/1001
/dev/loop18     4,3M  4,3M     0 100% /snap/tree/18

It seems that it's OK
2. `sudo lsof -Pn -i4 | grep :9200 | grep LISTEN` - nothing found

Where can be a problem?

**Comment by devhello145** [comment]
I catch it.
Utilize `1000:1000` as in instructions (see step 8)

**Comment by devhello145** [comment]
Thank you
