### ISSUE TITLE
Why run docker-compose with sudo?

### ISSUE THREAD

**Issue by wulftone** [allegroai/trains-server#48]
I saw the use of `sudo` in the [linux docs](https://github.com/allegroai/trains-server/blob/master/docs/install_linux_mac.md) for running the `docker` and `docker-compose up` commands.  What's the reason for this?  It doesn't seem like a good idea.  It seems to work fine in my testing without running with sudo.  Did you put your user into the `docker` group after installing docker?  That's the way the docker instructions say to run things.

**Comment by jkhenning** [comment]
Thanks @wulftone !
You are correct, `sudo` should be avoided (if possible) when launching a docker.
It seems like a copy/paste bug, I'll make sure this is fixed.
Updating here once docs are fixed & synced.

**Comment by bmartinn** [comment]
Hi @wulftone, just updating here that the documentation was fixed :)
