### ISSUE TITLE
Help - Is there a possibility to configure LDAP based Authentication?

### ISSUE THREAD

**Issue by jjose122** [allegroai/trains-server#51]

**Comment by bmartinn** [comment]
Hi @jjose122 ,

So the short answer, there is no support for LDAP (or any other single sign on) service :(

The idea of *trains-server* is to be a tool shared throughout the organization, accessible to everyone (hence the default, no password required setup). All in the hope of making the data-science work approachable to all engineers. Coupled with the ability to build / launch any experiment in the system with *trains-agent*, we hope we are able to help and make ML/DL apply for everyone.

That said, [Allegro.ai](https://allegro.ai) has a an enterprise version with LDAP authentication (as well as other providers), security roles etc. together with full data management and versioning suite, feel free to check the website :)

BTW:
There is a user/pass setup that you can configure manually, see details [here](https://github.com/allegroai/trains-server/blob/master/docs/faq.md#web-auth).

**Comment by jjose122** [comment]
Thank you @bmartinn. 
This information is helpful.
