### ISSUE TITLE
how to ssh login to AMI instance?

### ISSUE THREAD

**Issue by jinserk** [allegroai/trains-server#52]
I'm trying to use your AMI version of trains server, and it looks well accessible via web, but not via ssh.
What's the default user name of the image (both of the community version and the AWS marketplace version)?

**Comment by bmartinn** [comment]
Hi @jinserk 
The default user is the default AWS instance user `ec2-user` the SSH credentials you can control from the AWS console management (where you also spin instances from). Obviously do not forget to open your ssh port `tcp22` :)

**Comment by jinserk** [comment]
@bmartinn Thank you so much! I thought it's Ubuntu since the linux shows as `Other Linux`, not the `Amazon Linux`. `ec2-user` works well!
