### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by system123** [allegroai/trains-server#6]
Following the Docker installation instructions on Ubuntu 18.04 I end up with a page stating "Internal Server Error" when I try to access the webserver.

The last entry in the webserver logfile is:

[2019-06-25 09:51:57,329] [7] [INFO] [trains.webserver] ################ Web Server initializing #####################

**Comment by bmartinn** [comment]
Thanks @system123 , we managed to reproduce the bug.
Once we have an ETA on the fix I'll update here.
Should not take too long...

**Comment by bmartinn** [comment]
Seems like an issue with the mongoDB docker.
@system123 could you please run `docker ps` and make sure the mongodb docker is running properly (i.e. doesn't keep restarting)
Should look something like:

```
CONTAINER ID        IMAGE                                                  COMMAND                  CREATED             STATUS              PORTS               NAMES
9143ef2f16ba        allegroai/trains:latest                                "/opt/trains/wrapper…"   About an hour ago   Up About an hour                        trains-webserver
bdbcd4a2d818        allegroai/trains:latest                                "/opt/trains/wrapper…"   About an hour ago   Up About an hour                        trains-apiserver
5576dcb46624        allegroai/trains:latest                                "/opt/trains/wrapper…"   About an hour ago   Up About an hour                        trains-fileserver
f4d41f11872a        mongo:3.6.5                                            "docker-entrypoint.s…"   About an hour ago   Up 48 seconds                           trains-mongo
53e598b2ce79        docker.elastic.co/elasticsearch/elasticsearch:5.6.16   "/bin/bash bin/es-do…"   About an hour ago   Up About an hour                        trains-elastic
```

Let me know if the problem consists

**Comment by system123** [comment]
Thanks, I missed that Mongo had crashed, fixing that fixed the issue.
