### ISSUE TITLE
Invalid Interpolation format for "environment" option in service "agent-services": "${TRAINS_FILES_HOST:-}"

### ISSUE THREAD

**Issue by trathpai** [allegroai/trains-server#63]
While following instructions on [deploy](https://allegro.ai/docs/deploying_trains/trains_server_linux_mac/#deploying) i encounter the above error.

Is something missing?

Thanks

**Comment by jkhenning** [comment]
Hi @trathpai ,
Which docker-compose file are you using (standard, win10 etc.)?
Also, did you change anything in the docker-compose file, or did you get this error by using the latest docker-compose file with no change?

**Comment by jkhenning** [comment]
Also - which docker-compose version are you using?

**Comment by trathpai** [comment]
@jkhenning  i am using the one mentioned on the link [dockercompose](https://raw.githubusercontent.com/allegroai/trains-server/master/docker-compose.yml).

**Comment by trathpai** [comment]
I am using docker-compose version 1.17.1

**Comment by trathpai** [comment]
> Also - which docker-compose version are you using?

Ok upgrading the docker-compose to 1.24 solved it.
Thanks!

**Comment by jkhenning** [comment]
Hi @trathpai ,

Yeah, since the docker-compose.yml file specified `version: "3.6"` the minimum required version for docker-compose is 18.02.0
I'll make sure this appears in the documentation.

Thanks :)
