### ISSUE TITLE
Full multi-user support / security

### ISSUE THREAD

**Issue by fabio12345** [allegroai/trains-server#65]
Hi, firstly thanks for this - it's a great solution!
Are there plans for full multi user support? Currently, there doesn't seem to be a way to separate out access to files. For example, if user A wants to access something that needs authentication they will need to send all the credentials, fully unencrypted, to the server. That's not ideal for multi user scenarios: the server is shared, and all users can potentially access the data.
As an example, a secure NAS share. The user would have to mount the share, and do so by sending their credentials to the server; but all the users will be able to see the information about the credentials. Or am I missing something?

Thanks!

**Comment by bmartinn** [comment]
> Hi, firstly thanks for this - it's a great solution!

Thank you, @fabio12345 !

> For example, if user A wants to access something that needs authentication they will need to send all the credentials, fully unencrypted, to the server.

What do you mean by "send all the credentials" ? 
Are you referring to the S3 integration ? or the Login process ?
I think I missed the context (or setup) you have in mind :)

**Comment by fabio12345** [comment]
Sure, I'll try to be a bit more clear.

In the most generic case, I am thinking of the case when each user has some secret information that they don't want other users to be able to see, but that is needed during the training process, e.g. to access data. That could be login information for some service, or in my use case login information to a network drive. Each user needs to access a network drive, but access to the drive is controlled. As far as I understand, since the user can execute arbitrary python code nothing really prevents them from seeing other user's information on the same machine (for example, from a previous job).

**Comment by bmartinn** [comment]
> as I understand, since the user can execute arbitrary python code nothing really prevents them from seeing other user's information on the same machine

Not trivial, but yes that is doable (i.e. accessing the machine's data, obviously it depends on how you setup the `trains-agent` but it is not straight forward to make sure there is no leak)

> Looks like there is some support for "Cloud access" secrets in the UI

This is used by the browser session to access S3:// links, i.e. store access/private keys. Notice these keys are not stored on the trains-server, they are stored on the client's browser session. So on the one hand secure, on the other you cannot access them from code.
If you need these credentials in code, they are usually stored [here](https://github.com/allegroai/trains/blob/8b4b7098e014889a3806daa0be62450520aee033/docs/trains.conf#L77).
and are used automatically by the [StorageManager](https://allegro.ai/docs/examples/examples_storagehelper/#storagemanager) , when you access remote urls.

> ... have per-user secrets accessible ...

I think this is the bottom line, the system is designed to be used by trusted entities in the organization. 
Actually the idea is to share as much knowledge as possible among users.
For example, this is why it is assumed the `trains-agent`'s git credentials have read access for any repository in the organization.

If you are looking into tightening the security of the `trains` platform, I think you should probably see what they offer on the Enterprise level. These types of control are usually out of scope for most users of `trains` (I can just imagine the technical hurdles of making it work with additional layers of security ...). I do know they have LDAP connectivity and finer controlled user permissions.
I hope it helps :)

**Comment by fabio12345** [comment]
Thanks for your reply, very helpful!

> If you need these credentials in code, they are usually stored here.
> and are used automatically by the StorageManager , when you access remote urls.

would those be stored on that file on the client that creates the Task, on on the agent?

**Comment by bmartinn** [comment]
> would those be stored on that file on the client that creates the Task, on on the agent?

Actually on both, and they do not have to be identical.
The client has to have its credentials so that you can run your code on your machine and access remote URLs.
The agent has its own credentials (maybe with broader access) that are used when code is executed via the agent.
Following the security/permission discussion, there is nothing preventing you from abusing those credentials when running remotely ...
