### ISSUE TITLE
authentication error

### ISSUE THREAD

**Issue by urituval** [allegroai/trains-server#66]
Hello. It's our first trial with Trains.
1. Using remote cloud server (Linux Ubuntu18.06) as a host for Trains Server.    
2. Installed Trains Server on host using your Docker and docker-compose, complying to your "Deploying Trains Server: Linux and macOS" guide.
3. Forwarded the required 3 ports (localhost:8080, 8008, 8081) to local client and generated trains.conf configuration file ("Configuring Trains for Trains Server"): 
   api {
       # Notice: 'host' is the api server (default port 8008), not the web server.
       api_server: http://localhost:8008
       web_server: http://localhost:8080
       files_server: http://localhost:8081
       # Credentials are generated using the webapp, http://localhost:8080/profile
       # Override with os environment: TRAINS_API_ACCESS_KEY / TRAINS_API_SECRET_KEY
       credentials {"access_key": _KEY_, "secret_key": _KEY_}
   }
5. Put the code lines in a toy keras example:
   from trains import Task
   task = Task.init(project_name="Pima", task_name="my check")

Got this error:
Retrying (Retry(total=239, connect=239, read=240, redirect=240, status=240)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002411702BD90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /auth.login

 localhost:8080\dashboard shows empty dashboard

Tried:
1. Reset the server (down, up) - got the same problem
2. Using  Task.set_credentials(host='http://localhost:8008' ----)

Thanks for you assistance

**Comment by bmartinn** [comment]
Hi @urituval 
>  Forwarded the required 3 ports (localhost:8080, 8008, 8081)

Question, why do you need to forward the ports to the local client?
I would guess that you could gave setup the client with:
```
api_server: http://<server_ip_here>:8008
web_server: http://<server_ip_here>:8080
files_server: http://<server_ip_here>:8081
```
From the error it seems you are not actually reaching the trains-server...
Can you browse to "http://<server_ip_here>:8080" ?

**Comment by urituval** [comment]
Hi thanks for your answer.
First of all, it works now and this issue can be closed. 
I restarted the server and forwarded again the ports, and it's all good - with the same api{} I attached above.

For your questions: we are using a remote server that has only shell interface. First I forwarded the web server port, but then I had a problem in generating the credentials.  I followed your first reply to issue #28, and forwarded the other ports. Then when the config was generated, trains automatically set the localhost ports.

**Comment by bmartinn** [comment]
Looks good.
Do bear in mind that based on my understanding, for every client that will be using your trains-server, you will have to set the port forwarding. Maybe instead of SSH port forwarding, it might be easier to set a VPN and limit the access to the server based on that, just a thought :)

**Comment by NimaDL** [comment]
Hi @bmartinn, I was trying to connect clearml client to the clearml server running on EC2 instance in AWS. However, the setup configuration file can not reach out to the clearml server. the EC2 instance that clearml-sever is running on does not have Public IPv4 DNS and only has private IP address where the clearml-clint (running on another remote remote machine can not reach out to that). The error: 
## Retrying (Retry(total=239, connect=239, read=240, redirect=240, status=240)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f50e1505190>: Failed to establish a new connection: [Errno 111] Connection refused')': /auth.login
