### ISSUE TITLE
how to sense if trains is currently tracking experiment ?

### ISSUE THREAD

**Issue by eyalto** [allegroai/trains-server#7]
The trains can be imported by the current process, that may be tracking or may not be tracking.
In this case some external source code may want to change its behaviour if the current run is not tracked (perform something else than api call)

**Comment by bmartinn** [comment]
This is more of an SDK question, but nonetheless:

```
def is_trains_running():
    is_running = False
    import sys
    if 'trains' in sys.modules:
    	from trains import Task
    	is_running = Task.current_task() is not None
    return is_running
```

Is this what you were looking for?

**Comment by eyalto** [comment]
Yes - this is excellent now our code will be much more elegant with and without trains
