### ISSUE TITLE
How to update trains-server when using AWS AMI ?

### ISSUE THREAD

**Issue by eyalto** [allegroai/trains-server#8]
other than monitoring documentation / readme in the project page - any suggestions how to easily update the server (/services) ?

**Comment by bmartinn** [comment]
I assume you're referring to the issue of updating the server following a new release, in an AWS instance based on one of our AMIs. In that case, you will need to SSH into the machine and follow the [upgrade instructions](https://github.com/allegroai/trains-server#upgrade).

**Comment by eyalto** [comment]
Thanks a lot @bmartinn
