### ISSUE TITLE
Sub-domain configuration and authentication

### ISSUE THREAD

**Issue by shlomiken** [allegroai/trains-server#9]
Hi
i used the AMI to deplot to AWS. but i can see Everyone can login .
is there a guide for authentication ?
also - in the AMI deployment , where exactly is the trains-init script , could not find it , not even in the docker instances (webserver/api)
thanks
Shlomi

**Comment by bmartinn** [comment]
Moved issue to *TRAINS-server* for future reference.

**Comment by bmartinn** [comment]
@shlomiken did you manage to get the *TRAINS-server* working with your SageMaker pipeline ?

**Comment by shlomiken** [comment]
@bmartinn - still no , i have proceed with this , was waiting for you fix that will allow us to have the UI working with CORS / subdomains .

**Comment by bmartinn** [comment]
@shlomiken please check if the docker below solves the problem :)

`sudo docker run -d --restart="always" --name="trains-webserver" --network="host" -v /opt/trains/logs:/var/log/trains allegroai/trains:0.9.0-12 webserver`

**Comment by shlomiken** [comment]
@bmartinn - i don't run the docker myself , i remind you i have used the AMI deployment.

**Comment by bmartinn** [comment]
@shlomiken sure, *TRAINS-server* **0.9.0-12** AMI IDs by regions:

eu-north-1 - ami-05a6e3ee78b647f97
ap-south-1 - ami-0d3edec2c2bc0155a
eu-west-3 - ami-0a1c4262f942e656d
eu-west-2 - ami-0ea8ca5fce67531c5
eu-west-1 - ami-067c828528a5203ee
ap-northeast-2 - ami-0588366d62f372702
ap-northeast-1 - ami-0395d3e7aef0f1c39
sa-east-1 - ami-08017fcb4f3a3a3f9
ca-central-1 - ami-0399f2bf57c9c4aa3
ap-southeast-1 - ami-0a2b780c64670beb9
ap-southeast-2 - ami-0a627401b844c3960
eu-central-1 - ami-0e6f580ffbd6d2fd1
us-east-2 - ami-0245c5960be5a67b5
us-west-1 - ami-04320deaf0fab4e29
us-west-2 - ami-0f632602fb4f8e9bd

**Comment by shlomiken** [comment]
is there a reason us-east-1 is not on the list ?

**Comment by shlomiken** [comment]
@bmartinn - looks like the image on us-east-1 is an old version ? 0.0.39 
![image](https://user-images.githubusercontent.com/32815285/60447384-094c4c00-9c2c-11e9-9b79-d847a05c4923.png)
while those you sent are 0.9

**Comment by bmartinn** [comment]
Oops :)
us-east-1 ami-0f6518bfa76238051

**Comment by shlomiken** [comment]
@bmartinn - i cannot find it in us-east-1

**Comment by bmartinn** [comment]
It seems that for some reason the us-east-1 AMI wan't public. Please try again now.

**Comment by shlomiken** [comment]
@bmartinn - still get a problem in UI , API requests are going to trainsapp.kenshoo-lab.com instead of trainsapi.kenshoo-lab.com
![image](https://user-images.githubusercontent.com/32815285/60452231-c2b01f00-9c36-11e9-8c80-1050160100b7.png)

**Comment by bmartinn** [comment]
@shlomiken please note the Web-App will replace the "app" *prefix* with "api" prefix.
In order to get the UI working, please try to set the subdomains as following:
```
app.trains.kenshoo-lab.com
api.trains.kenshoo-lab.com

```

**Comment by shlomiken** [comment]
@bmartinn done that - unfortunately still not working, now its 401 unauthorized. maybe the 3 parts domain name ?

![image](https://user-images.githubusercontent.com/32815285/60468519-8f838500-9c62-11e9-8d83-9e0297e5f73b.png)

**Comment by bmartinn** [comment]
We've investigated this issue and found out the culprit is probably the authentication cookie's domain configuration. We'll release a new version very soon to allow configuring these kind of properties from outside the docker containers. I'll update when the new version is out.

**Comment by bmartinn** [comment]
Hi,
There's a new version out (0.10.0) that supports external configuration.
See the updated documentation's [Configuration](https://github.com/allegroai/trains-server/blob/master/README.md#configuration) section for configuring the server, and the [Upgrade](https://github.com/allegroai/trains-server#upgrade) section for upgrading the server to the latest version.

In order to configure the authentication cookie domain to your domain, you'll need to place a `webserver.conf` file in the mapped config directory with the following configuration:
```
auth {
    cookies {
        domain: "trains.kenshoo-lab.com"
    }
}
```
Please note:
- You'll need to add this configuration file before running the new docker containers
- Since you're using two sub-domains (`app.trains...`), you might need to use `kenshoo-lab.com` as the cookie's domain

**Comment by shlomiken** [comment]
@bmartinn - Hi i have just deployed the new version (again i'm using AMI not docker directly) 
i have placed webserver.conf in the web server container . as you specified above  and still get 405 method not allowed.
i think you are missing something 
The cookie domain should not be configured - it should be taken from the request url (most server in the world works like this) 
cause now for example i cannot access the instance directly at port 8080 - it just redirects back to the login page.

**Comment by bmartinn** [comment]
@shlomiken a new version is out (0.10.1), and we've replaced the webserver with NGINX, which should simplify things.

The configuration you should need with this new version, assuming you are using HTTPS and your primary domain is `trains.kenshoo-lab.com`:
- An `/opt/trains/config/apiserver.conf` file, containing:
```
auth {
  cookies {
    httponly: true
    secure: true
    domain: ".trains.kenshoo-lab.com"
    max_age: 99999999999
  }
}
```
- The following load balancer configuration:
    - Listeners:
        - (optional) HTTP listener, that redirects all traffic to HTTPS.
        - HTTPS listener for app.<domain> forwarded to 'AppTargetGroup'
        - HTTPS listener for api.<domain> forwarded to 'ApiTargetGroup'
        - HTTPS listener for files.<domain> forwarded to 'FilesTargetGroup'
    - Target groups:
        - AppTargetGroup: HTTP based target group, port 8080
        - ApiTargetGroup: HTTP based target group, port 8008
        - FilesTargetGroup: HTTP based target group, port 8081
    - Security and routing:
        - Load balancer: Make sure the load balancers are able to receive traffic from the relevant IP addresses (Security groups and Subnets definitions).
        - Instances: Make sure the load balancers are able to access the instances, using the relevant ports (Security groups definitions).

Make sure you either use our AMIs or run the docker containers with the updated `docker run` commands (see the updated [Launching Docker Containers](https://github.com/allegroai/trains-server#launching-docker-containers)).

**Comment by shlomiken** [comment]
thanks @bmartinn 
can you be more specific about the version - i can see in AWS version allegroai-trains-server-0.10.1-101
should i use it ?
by having a config file file i guess you want me to create it in the AWS instance and then restart the service / instance ?
thanks
Shlomi

**Comment by bmartinn** [comment]
You should use the `allegroai-trains-server-0.10.1-1` AMIs (AMI id `ami-0f2e1f2d006287666` for `us-east-1`).
As far as configuration goes, you're correct - after creating the instance based on the AMI, you should ssh into the machine, add the `apiserver.conf`, than `docker stop`, `docker rm` and `docker run` the `trains-apiserver` container according to the instructions in the Upgrade section.

**Comment by bmartinn** [comment]
@shlomiken was the problem solved? 
We added a per service configuration to the TRAINS python package (starting [v0.10.3](https://github.com/allegroai/trains/releases/tag/0.10.3)) 
You can find configuration example [here](https://github.com/allegroai/trains/blob/master/docs/trains.conf#L3)
Is it working for you?

**Comment by bmartinn** [comment]
Closing, due to lack of activity.
